language: python

jdk:
- openjdk8

services:
  - docker

sudo: required

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}

script:
- bin/build

notifications:
  slack:
    rooms:
      - lcmap:UTqlh9PfPVomfpli10WKyZoh#cicd