language: c

sudo: required

services:
  - docker

script: make build && make tag

deploy:
  - provider: script
    script: make push
    on:
      all_branches: true

notifications:
  slack:
    rooms:
      - lcmap:UTqlh9PfPVomfpli10WKyZoh#cicd
